[project]
name = "python-pdm-template"
description = "A Project Template of Python with PDM"
dynamic = ["version"]
authors = [{ name = "Du Shiqiao", email = "lucidfrontier.45@gmail.com" }]
license = { text = "MIT" }
requires-python = ">=3.9"
dependencies = ["fastapi>=0.79.0", "uvicorn[standard]>=0.18.2"]

[project.optional-dependencies]
server = ["gunicorn>=20.1.0"]

[project.scripts]
app = "app.cli:main"

[build-system]
requires = ["pdm-pep517>=1.0.0"]
build-backend = "pdm.pep517.api"

[tool.pdm]
version = { source = "file", path = "src/app/version.py" }

[tool.pdm.dev-dependencies]
dev = ["mypy>=0.991", "black>=22.12.0", "pytest-cov>=4.0.0", "ruff>=0.0.195"]

[tool.pdm.scripts]
black = "black ."
mypy = "mypy --show-column-numbers ."
ruff_lint = "ruff ."
ruff_fix = "ruff --fix-only ."
test = "pytest tests --cov=app --cov-report=term --cov-report=xml"
format = { composite = ["black", "ruff_fix"] }
lint = { composite = ["ruff_lint", "mypy"] }
check = { composite = ["format", "lint", "test"] }

[tool.pytest.ini_options]
filterwarnings = ["ignore::FutureWarning"]

[tool.black]
target-version = ["py39"]

[tool.ruff]
target-version = "py39"

[tool.mypy]
exclude = ["tests", "dist"]
python_version = "3.9"
check_untyped_defs = true
warn_return_any = true
warn_unused_ignores = true
no_implicit_optional = true
show_error_codes = true
strict_equality = true

# [[tool.mypy.overrides]]
# module = "external_lib.*"
# ignore_missing_imports = true
